




apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  type: NodePort
  selector:
    matchLabels:
      app: server
  replicas: 2
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        build: e_commerce/server:1
        ports:
          - containerPort: 3000
        command: ["sh","-c"]
        args: ["npm run seed:db admin@devops.com admin123 && npm start"]
        env:
          - name: PORT
            value: "3000"
          - name: BASE_API_URL
            value: api
          - name: CLIENT_URL
            value: http://localhost:4000
          - name: JWT_SECRET
            value: update_your_JWT_secret
          - name: MONGO_URI
            value: mongodb://mongo:27017/mern_ecommerce